package vistas;

import datos.JDBCDAO;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import modelo.Multa;
import modelo.MultaTipo;
import modelo.Policia;

public class MultasIntroducir extends javax.swing.JDialog {

    /**
     * Creates new form MultasIntroducir
     */
    JDBCDAO jd_multas;

    public MultasIntroducir(java.awt.Frame parent, boolean modal, JDBCDAO jdbcdao) {
        super(parent, modal);
        initComponents();
        this.setTitle("Introducción de Multas");
        this.setLocationRelativeTo(null);
        jd_multas = jdbcdao;

        //Lista auxiliar
        DefaultListModel modelo = new DefaultListModel();

        //Carga de Datos
        int id = Integer.parseInt(jd_multas.recogerUltimo("multas","id")) + 1;
        multaID.setText(Integer.toString(id));

        try {
            for (MultaTipo mt : jd_multas.recogerMultasTipo()) {
                TipoCombox.addItem(mt);
            }

            for (Policia p : jd_multas.MostrarPolicias("idPolicia")) {
                modelo.addElement(p);

            }
            this.PoliciaList.setModel(modelo);

        } catch (SQLException ex) {
            Logger.getLogger(MultasIntroducir.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InsertarMulta = new javax.swing.JButton();
        ImporteSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PoliciaList = new javax.swing.JList();
        TipoCombox = new javax.swing.JComboBox();
        multaID = new javax.swing.JLabel();
        nifFormatted = new javax.swing.JFormattedTextField();
        FechaChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescripcionField = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(" Policía");

        jLabel3.setText("Descripción");

        jLabel4.setText("Fecha");

        jLabel5.setText("Importe");

        InsertarMulta.setText("Insertar Multa");
        InsertarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarMultaActionPerformed(evt);
            }
        });

        jLabel6.setText("NIF Infractor");

        jLabel7.setText("Tipo Multa");

        jScrollPane1.setViewportView(PoliciaList);

        TipoCombox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TipoComboxItemStateChanged(evt);
            }
        });

        multaID.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        try {
            nifFormatted.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        FechaChooser.setDateFormatString("yyyy-MM-dd HH:mm:ss");

        DescripcionField.setColumns(20);
        DescripcionField.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        DescripcionField.setRows(4);
        jScrollPane2.setViewportView(DescripcionField);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setText("Multa nº");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImporteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InsertarMulta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nifFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(41, 41, 41)
                                .addComponent(FechaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multaID, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(multaID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nifFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(FechaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ImporteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertarMulta))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarMultaActionPerformed
        // Variables
        String descripcion, nifInfractor;
        java.util.Date fecha_java;
        Timestamp fecha_sql;
        double importe;
        int idMulta, idPolicia, idTipo;
        Policia p;
        MultaTipo mt;

        try {
            //Recogida de datos
            descripcion = DescripcionField.getText();
            if (DescripcionField.getText().isEmpty()) {
                descripcion = null;
            }

            fecha_java = FechaChooser.getDate();
            fecha_sql = new Timestamp(fecha_java.getTime());

            importe = Double.parseDouble(ImporteSpinner.getValue().toString());

            p = (Policia) PoliciaList.getSelectedValue();
            idPolicia = p.getIdPolicia();

            nifInfractor = nifFormatted.getText();
            if (nifInfractor.equalsIgnoreCase("        - ")) {
                nifInfractor = null;
            }

            mt = (MultaTipo) TipoCombox.getSelectedItem();
            idTipo = mt.getId();
            
            //Creación de objetos e insertar datos
            Multa m = new Multa(descripcion, fecha_sql, importe, idPolicia, nifInfractor, idTipo);

            jd_multas.introducirMulta(m);
            JOptionPane.showMessageDialog(this, "La Multa ha sido insertada Correctamente.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            
            idMulta = Integer.parseInt(multaID.getText()) + 1;
            multaID.setText(Integer.toString(idMulta));
        } catch (SQLException | NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "No se ha podido insertar la multa correctamente.\nHay campos vacios o incorrectos.\nError: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        //Comprobación de campos
        if (DescripcionField.getText().isEmpty()) {
            DescripcionField.setBorder(new LineBorder(java.awt.Color.RED));
        } else {
            DescripcionField.setBorder(null);
        }

        if (PoliciaList.getSelectedValue() == null) {
            PoliciaList.setBorder(new LineBorder(java.awt.Color.RED));
        } else {
            PoliciaList.setBorder(null);
        }

        if (FechaChooser.getDate() == null) {
            FechaChooser.setBorder(new LineBorder(java.awt.Color.RED));
        } else {
            FechaChooser.setBorder(null);
        }

    }//GEN-LAST:event_InsertarMultaActionPerformed

    private void TipoComboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoComboxItemStateChanged

        try {
            for (MultaTipo mt : jd_multas.recogerMultasTipo()) {
                if (this.TipoCombox.getSelectedItem().toString().equalsIgnoreCase(mt.toString())) {
                    this.ImporteSpinner.setValue(mt.getImporte());
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MultasIntroducir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TipoComboxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DescripcionField;
    private com.toedter.calendar.JDateChooser FechaChooser;
    private javax.swing.JSpinner ImporteSpinner;
    private javax.swing.JButton InsertarMulta;
    private javax.swing.JList PoliciaList;
    private javax.swing.JComboBox TipoCombox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel multaID;
    private javax.swing.JFormattedTextField nifFormatted;
    // End of variables declaration//GEN-END:variables
}
